version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-228-212-134.eu-west-1.compute.amazonaws.com
            database: d7757i9e0s79mr
            user: xvmvvvgmirzoji
            ssl: true
            password: 425a158900ae1428eb9a15b6b386b0fe33a6c36d5eec71705a49e9816aee3853
            rawAccess: true
            port: '5432'
            migrations: true
